# Adapted from the example site config from the Bear Blog theme

baseURL = "https://max.davitt.me"
theme = "hugo-maxbear"
title = "Max's Stuff"
author = "Max Davitt"
languageCode = "en-US"
timeZone = "America/New_York"

disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
capitalizeListTitles = false

enableGitInfo = true

[params]
  # The "description" of your website. This is used in the meta data of your generated html.
  description = "Max Davitt's personal website"

  # Another "title" :-). This one is used as the site_name on the Hugo's internal
  # opengraph structured data template.
  # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
  title = "Max's Stuff"

  # By default, this theme displays dates with a format like "02 Jan, 2006", but
  # you can customize it by setting the `dateFormat` param in your site's config
  # file. See [Hugo's Format function docs](https://gohugo.io/functions/format/)
  # for details. An example TOML config that uses [ISO
  # 8601](https://en.wikipedia.org/wiki/ISO_8601) format:
  dateFormat = "2006-01-02"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      strikethrough = false
      [markup.goldmark.extensions.extras]
        [markup.goldmark.extensions.extras.delete]
          enable = true
        [markup.goldmark.extensions.extras.insert]
          enable = true
        [markup.goldmark.extensions.extras.mark]
          enable = true
    [markup.goldmark.parser]
      autoHeadingID = false
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    noClasses = false

[outputs]
  home = ["HTML"]

[minify]
  minifyOutput = true

[frontmatter]
  lastmod = [':git', ':fileModTime', ':default']

[permalinks]
  tags = "/blog/tags/:slug/"