# Adapted from the example site config from the Bear Blog theme

baseURL = "https://max.davitt.me"
theme = "hugo-bearblog"
title = "Max's Stuff"
author = "Max Davitt"
languageCode = "en-US"

enableRobotsTXT = true

disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]

[params]
  # The "description" of your website. This is used in the meta data of your generated html.
  description = "Max Davitt's personal website"

  # Another "title" :-). This one is used as the site_name on the Hugo's internal
  # opengraph structured data template.
  # See https://ogp.me/ and https://gohugo.io/templates/internal#open-graph.
  title = "Max's Stuff"

  # This theme will, by default, inject a made-with-line at the bottom of the page.
  # You can turn it off, but we would really appreciate if you don’t :-).
  hideMadeWithLine = true

  # By default, this theme displays dates with a format like "02 Jan, 2006", but
  # you can customize it by setting the `dateFormat` param in your site's config
  # file. See [Hugo's Format function docs](https://gohugo.io/functions/format/)
  # for details. An example TOML config that uses [ISO
  # 8601](https://en.wikipedia.org/wiki/ISO_8601) format:
  dateFormat = "2006-01-02"

[markup.goldmark.renderer]
  unsafe = true

[outputs]
  home = ["HTML"]

[minify]
  minifyOutput = true
