name: Build & Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: true

      - name: Setup SSH key
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: |
          ssh-agent -a $SSH_AUTH_SOCK > /dev/null
          ssh-add - <<< "${{ secrets.SSH_PRIVATE_KEY }}"

      - name: Cache Hugo
        id: cache-hugo
        uses: actions/cache@v3
        with:
          path: /usr/local/bin/hugo
          key: ${{ runner.os }}-hugo

      - name: Install Hugo
        if: steps.cache-hugo.outputs.cache-hit != 'true'
        run: |
          curl -LOC- https://github.com/gohugoio/hugo/releases/download/v0.107.0/hugo_0.107.0_linux-amd64.tar.gz
          tar -xvzf hugo_*.tar.gz hugo
          mv hugo /usr/local/bin
          rm hugo_*.tar.gz
          hugo version

      - name: Build
        run: hugo

      - name: Deploy
        env:
          SSH_AUTH_SOCK: /tmp/ssh_agent.sock
        run: rsync -e "ssh -o StrictHostKeyChecking=no -o LogLevel=ERROR" -avz public/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/public/max.davitt.me/
